steps:
- task: AzureCLI@1
  displayName: 'Azure CLI '
  inputs:
    azureSubscription: {azure-subscription}
    scriptLocation: inlineScript
    inlineScript: 'az webapp deployment source config-zip --resource-group {azure-resource-group} --name {app-service-name} --src package.zip'
    workingDirectory: '$(System.DefaultWorkingDirectory)/{LinkedArtifact}/drop'
